Add skeleton scripts for af6 and status in utilities
FredHutch/nlp-airflow-dags pull request #116
Opened 2020-04-09 01:00 UTC by ritchelong

Taking some boilerplate from af5 to stamp out some necessary functions in our workflow -> eg create an id, tie it to a date, log it and run a task.

Need to remedy what will be in place of resynth dates from this task, as my understanding this is pulling from swift to perform it? 

I should have asked earlier about the distinction between using resynth dates and stuff at this point in the code. That's up to clarify in tying it with af6 job ids.

DB in the nlp db should be up for af6

2020-04-09 15:37 UTC, WhiteAu requested changes
There are unfinished merge conflicts in the code, and some fundamental name mismatches here.

2020-04-09 15:37 UTC, WhiteAu commented on active/af6-bort.py
> +=======
looks like you have some merge conflicts here, still.

2020-04-09 15:37 UTC, WhiteAu commented on active/operators/bort/generate_job_id.py
> +<<<<<<< HEAD
merge conflict

2020-04-09 15:37 UTC, WhiteAu commented on active/operators/bort/generate_job_id.py
> +>>>>>>> b971b26922305b16fba3df263b1a220425ce9d97
looks like the choice is to keep this entire module or not-- keep it!

2020-04-09 15:37 UTC, WhiteAu commented on active/operators/bort/populate_blobid_in_job_table.py
> +<<<<<<< HEAD
merge conflict

2020-04-09 15:37 UTC, WhiteAu commented on active/af6-bort.py
> +from operators.bort import generate_job_id, populate_blobid_in_job_table, run_bort_task
imported as run_bort_task (singular) here, but invoked below as run_bort_tasks (plural)
Which is it? I'd assume plural, but this should be the same regardless.

2020-04-09 15:37 UTC, WhiteAu commented on active/af6-bort.py
> +generate_job_id >> populate_blobid_in_job_table_operator >> run_bort_tasks
run_ner_tasks vs run_bort_tasks vs run_ner_borts_tasks

these should be a single name.

2020-04-09 15:37 UTC, WhiteAu commented on active/af6-bort.py
> +from operators.bort import generate_job_id, populate_blobid_in_job_table, run_bort_task
this reminds me: I am going to add a TODO in the backlog to unify our generate_job_id/populate_job_id fn's into a single module that everything can call.

2020-04-09 15:37 UTC, WhiteAu commented on active/af6-bort.py
> +populate_blobid_in_job_table_operator = \
is this the naming convention we've been using elsewhere? I like it, but presently this is the only dag Operator that follows this convention. Unify to either *All* operators use this naming, or *None* imo

2020-04-09 15:37 UTC, WhiteAu commented on active/operators/bort/generate_job_id.py
> +    return new_run_id, bortdates
is bortdates supposed to be last_bort_update_date?

2020-04-09 15:37 UTC, WhiteAu commented on active/operators/bort/run_ner_tasks.py
> +def run_bort_task(**kwargs):
run_bort_task vs run_bort_tasks?
this function looks like it's going to run over multiple tasks (there's a loop)

2020-04-09 17:22 UTC, esilgard commented on active/af6-bort.py
> +                   provide_context=True,
saveto_source vs save_to_source

2020-04-09 21:01 UTC, esilgard commented
testing email notification delivery
    On Thursday, April 9, 2020, 08:37:22 AM PDT, A White <notifications@github.com> wrote:  
 
 


@WhiteAu requested changes on this pull request.

There are unfinished merge conflicts in the code, and some fundamental name mismatches here.

In active/af6-bort.py:
> +<<<<<<< HEAD
+run_ner_tasks= \
+    PythonOperator(task_id='run_ner_borts_tasks',
+                   provide_context=True,
+                   python_callable=run_bort_tasks,
+                   dag=dag)
+
+
+generate_job_id >> populate_blobid_in_job_table_operator >> run_bort_tasks
+=======

looks like you have some merge conflicts here, still.

In active/operators/bort/generate_job_id.py:
> @@ -0,0 +1,74 @@
+from datetime import datetime
+
+import utilities.common_variables as common_variables
+import utilities.common_hooks as common_hooks
+from airflow.operators.python_operator import PythonOperator
+
+<<<<<<< HEAD

merge conflict

In active/operators/bort/generate_job_id.py:
> +=======
+>>>>>>> b971b26922305b16fba3df263b1a220425ce9d97

looks like the choice is to keep this entire module or not-- keep it!

In active/operators/bort/populate_blobid_in_job_table.py:
> @@ -0,0 +1,32 @@
+from datetime import datetime
+
+import utilities.common_hooks as common_hooks
+import utilities.common_variables as common_variables
+
+<<<<<<< HEAD

merge conflict

In active/af6-bort.py:
> @@ -0,0 +1,57 @@
+from datetime import datetime, timedelta
+
+from airflow.operators.python_operator import PythonOperator
+from airflow.models import DAG
+from operators.bort import generate_job_id, populate_blobid_in_job_table, run_bort_task

imported as run_bort_task (singular) here, but invoked below as run_bort_tasks (plural)
Which is it? I'd assume plural, but this should be the same regardless.

In active/af6-bort.py:
> +run_ner_tasks= \
+    PythonOperator(task_id='run_ner_borts_tasks',
+                   provide_context=True,
+                   python_callable=run_bort_tasks,
+                   dag=dag)
+
+
+generate_job_id >> populate_blobid_in_job_table_operator >> run_bort_tasks

run_ner_tasks vs run_bort_tasks vs run_ner_borts_tasks

these should be a single name.

In active/af6-bort.py:
> @@ -0,0 +1,57 @@
+from datetime import datetime, timedelta
+
+from airflow.operators.python_operator import PythonOperator
+from airflow.models import DAG
+from operators.bort import generate_job_id, populate_blobid_in_job_table, run_bort_task

this reminds me: I am going to add a TODO in the backlog to unify our generate_job_id/populate_job_id fn's into a single module that everything can call.

In active/af6-bort.py:
> +    'retry_delay': timedelta(minutes=5),
+}
+
+dag = DAG(dag_id=DAG_NAME,
+          default_args=args,
+          dagrun_timeout=timedelta(seconds=30))
+
+generate_job_id = \
+    PythonOperator(task_id='generate_job_id',
+                   provide_context=True,
+                   python_callable=generate_job_id,
+                   dag=dag)
+
+
+
+populate_blobid_in_job_table_operator = \

is this the naming convention we've been using elsewhere? I like it, but presently this is the only dag Operator that follows this convention. Unify to either All operators use this naming, or None imo

In active/operators/bort/generate_job_id.py:
> +
+    if last_run_id is None:
+        new_run_id = 1
+    else:
+        new_run_id = last_run_id + 1
+
+    if last_bort_update_date is None:
+        last_bort_update_date = common_variables.EPOCH
+    print("starting batch run ID: {id} of blobs since {date}".format(id=new_run_id,
+                                                                     date=last_bort_update_date))
+    # get last update date from source since last successful run
+    # then pull record id with new update date from source
+    job_start_date = datetime.now().strftime(common_variables.DT_FORMAT)[:-3]
+
+
+    return new_run_id, bortdates

is bortdates supposed to be last_bort_update_date?

In active/operators/bort/run_ner_tasks.py:
> @@ -0,0 +1,42 @@
+import json
+from datetime import datetime
+
+import utilities.common_variables as common_variables
+import utilities.common_hooks as common_hooks
+import utilities.common_functions as common_functions
+#TODO: add prospective BERT endpoint in utilities?
+
+
+def run_bort_task(**kwargs):

run_bort_task vs run_bort_tasks?
this function looks like it's going to run over multiple tasks (there's a loop)


—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-04-13 15:51 UTC, esilgard approved these changes
fix up the run_bort_task import in af6-bort.py

2020-04-13 23:03 UTC, esilgard approved these changes
let's get this merged in before the development branch grows further

2020-04-14 16:32 UTC, merged